name: Laravel Package CI

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  laravel_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction
        
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
